apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-output-claim
        - name: information
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: log-writer
          image: capscience/log-writer:1.11.1
          env:
            - name: LOG_PATH
              value: "/logs/log.txt"
          volumeMounts:
            - name: shared-logs
              mountPath: /logs
        - name: log-api
          image: capscience/log-api:4.1.2
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: PORT
              value: "3000"
            - name: LOG_PATH
              value: "/logs/log.txt"
            - name: PINGS_ENDPOINT
              value: "http://pingpong-svc:2345/pings"
            - name: INFO_PATH
              value: /info/information.txt
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-logs
              mountPath: /logs
            - name: information
              mountPath: /info
