apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: log-writer
          image: capscience/log-writer:1.11.1
          env:
            - name: LOG_PATH
              value: "/logs/log.txt"
          volumeMounts:
            - name: shared-logs
              mountPath: /logs
        - name: log-api
          image: capscience/log-api:2.1.1
          env:
            - name: PORT
              value: "3000"
            - name: LOG_PATH
              value: "/logs/log.txt"
            - name: PINGS_ENDPOINT
              value: "http://pingpong-svc:2345/pings"
          volumeMounts:
            - name: shared-logs
              mountPath: /logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pings
          emptyDir: {}
      containers:
        - name: pingpong
          image: capscience/pingpong:2.1.1
          env:
            - name: PORT
              value: "3000"
            - name: PINGPONG_PATH
              value: "/logs/pingpong.txt"
          volumeMounts:
            - name: pings
              mountPath: /logs
