apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: project
data:
  PORT: "3000"
  IMAGE_URL: https://picsum.photos/1200
  IMAGE_PATH: /usr/src/app/images/hourly-image.jpg
  IMAGE_TTL_SECONDS: "600"
